In [ ]:
from os import EX_TEMPFAIL
# Inheritance
class Student:
  def __init__(self,name,id,number):
    self.name = name
    self.id = id
    self.number = number

  def print(self):
    print(f"Name of the student : {self.name}\nId : {self.id}\nNumber : {self.number}")

class personal_info(Student):

  def info(self,email):
    self.email = email
    print(f"Name of the student : {self.name}\nId : {self.id}\nEmail : {self.email}")


#student = Student("Romi",12,1234)
#student.print()
x = personal_info("Romi",12,1234)
x.info("abc@gmail.com")


Name of the student : Romi
Id : 12
Email : abc@gmail.com


In [ ]:
import numpy as np
monthly_sales = np.array([200, 220, 250, 275, 300, 320,
                          350, 370, 400, 420, 450, 475])

In [ ]:
print(f"January {monthly_sales[0]}")
print(f"December {monthly_sales[11]}")

January 200
December 475


In [ ]:
q1 = monthly_sales[:3]
print(q1)
q2 = monthly_sales[3:6]
print(q2)
q3 = monthly_sales[6:9]
print(q3)
q4 = monthly_sales[9:]
print(q4)

[200 220 250]
[275 300 320]
[350 370 400]
[420 450 475]


In [ ]:
monthly_sales[3] = 280
print(monthly_sales[3])

280


In [ ]:
x = monthly_sales[5:8]
print(x)
np.mean(monthly_sales[5:8])

[320 350 370]


346.6666666666667

In [22]:
import numpy as np
monthly_sale = np.random.randint(100,500,12)
print(monthly_sale)

discounted_sale = []
for i in monthly_sale:

  discounted_sale.append(i*0.9)
print(discounted_sale)


[105 270 444 424 163 212 322 471 331 170 481 249]
[94.5, 243.0, 399.6, 381.6, 146.70000000000002, 190.8, 289.8, 423.90000000000003, 297.90000000000003, 153.0, 432.90000000000003, 224.1]


In [27]:
import numpy as np
def age_stage(age):
  if age<18:
    return "Children"
  elif age>=18 and age<65:
    return "Adult"
  else:
    return "Senior Citizen"
age_stage = np.vectorize(age_stage)
arr = np.array([21,12,35,65,9])
age_stage(arr)


array(['Adult', 'Children', 'Adult', 'Senior Citizen', 'Children'],
      dtype='<U14')

In [34]:
import numpy as np
data = np.random.randint(10,100,25)
data = data.reshape(5,5)
data

array([[11, 33, 22, 35, 26],
       [14, 68, 77, 48, 49],
       [44, 76, 51, 57, 40],
       [11, 75, 76, 12, 22],
       [49, 40, 87, 27, 85]])

In [41]:
import numpy as np
data = np.random.randint(10,100,25)

print(np.vstack(data))
np.hstack(data)

[[81]
 [82]
 [27]
 [84]
 [75]
 [74]
 [58]
 [64]
 [85]
 [28]
 [10]
 [22]
 [33]
 [90]
 [13]
 [50]
 [43]
 [80]
 [43]
 [40]
 [61]
 [79]
 [31]
 [17]
 [14]]


array([81, 82, 27, 84, 75, 74, 58, 64, 85, 28, 10, 22, 33, 90, 13, 50, 43,
       80, 43, 40, 61, 79, 31, 17, 14])

In [46]:
import numpy as np
Shopping_list = [87,np.nan,89,90]

np.isnan(Shopping_list)

array([False,  True, False, False])

In [49]:
np.nanmean(Shopping_list)


88.66666666666667